// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUYxQdHO_AHvz2twsvIOA2fa0rKaotjM',
    appId: '1:836090399057:web:000f4d29beaa52dbd92b70',
    messagingSenderId: '836090399057',
    projectId: 'chatapptut-9f368',
    authDomain: 'chatapptut-9f368.firebaseapp.com',
    storageBucket: 'chatapptut-9f368.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIp8NP8wfbFyMq5i9kmNt86HQLkmZtJYM',
    appId: '1:836090399057:android:af22eb711e28757dd92b70',
    messagingSenderId: '836090399057',
    projectId: 'chatapptut-9f368',
    storageBucket: 'chatapptut-9f368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9vp1WUvVJ0LzLAXNogoroXfBvyB5xKdc',
    appId: '1:836090399057:ios:63d49db65de54e67d92b70',
    messagingSenderId: '836090399057',
    projectId: 'chatapptut-9f368',
    storageBucket: 'chatapptut-9f368.firebasestorage.app',
    iosBundleId: 'com.example.chatAppMk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9vp1WUvVJ0LzLAXNogoroXfBvyB5xKdc',
    appId: '1:836090399057:ios:63d49db65de54e67d92b70',
    messagingSenderId: '836090399057',
    projectId: 'chatapptut-9f368',
    storageBucket: 'chatapptut-9f368.firebasestorage.app',
    iosBundleId: 'com.example.chatAppMk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdUYxQdHO_AHvz2twsvIOA2fa0rKaotjM',
    appId: '1:836090399057:web:5d2ab759d7fa3731d92b70',
    messagingSenderId: '836090399057',
    projectId: 'chatapptut-9f368',
    authDomain: 'chatapptut-9f368.firebaseapp.com',
    storageBucket: 'chatapptut-9f368.firebasestorage.app',
  );
}
